### ISSUE TITLE
Suggestion: Toggle on/off enviromental effects in playermenu and change far -near settings

### ISSUE THREAD

**Issue by ancientevil** [LouDnl/ArmA3_Wasteland.Altis#36]
Found it from "creampie". Works very well on server and set viewdistance and grass in playermenu.

This works very well for low end computers (near) to high end for far viewing range

commit:7104f654cfaf5cd8dec41246aba3d4041c2de0ff

https://github.com/ancientevil/ArmA3_Wasteland.Stratis/commit/7104f654cfaf5cd8dec41246aba3d4041c2de0ff

**Comment by LouDnl** [comment]
I used to have a custom button for viewdistance settings. This is disabled as it creates an unfair advantage for players with super computers. Far gives a maximum of 3300 view and object distance. Perfect for Wasteland.

I have disabled the environmental effects for all players atm because of the rabbits causing lag. This is already fixed in dev Arma 3. When this hits stable I will re-enable all environmental effects.

**Comment by ancientevil** [comment]
Ok sounds well reasoned. I will try this setting a while because this toggle setting can be adjusted toi make it fair?

onButtonClick = "setViewDistance 1000; setObjectViewDistance 900; setTerrainGrid 50;";

Perhaps i merge back to main when official "fix" comes!
